name: CI

on:
  push:

jobs:
  deploy:
    permissions:
      contents: read
      packages: write

    uses: IIS-Design/.github/.github/workflows/container-deploy.yml@main

    with:
      app: astra
      container-port: 80
      smoke-path: /astra/p1/website/homepage/
